/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary": "#003915",
        "inverse-primary": "#b91a24",
        "tertiary-fixed": "#ffdf9a",
        "on-background": "#dae2fd",
        "on-tertiary": "#3f2e00",
        "outline-variant": "#5b403e",
        "surface-container": "#171f33",
        "on-primary-container": "#5c0008",
        "on-tertiary-container": "#372700",
        "on-secondary-fixed": "#002109",
        "error-container": "#93000a",
        "tertiary": "#f7be1d",
        "on-secondary-fixed-variant": "#005321",
        "inverse-surface": "#dae2fd",
        "secondary-fixed-dim": "#4ae176",
        "tertiary-fixed-dim": "#f7be1d",
        "surface-container-lowest": "#060e20",
        "surface-tint": "#ffb3ad",
        "primary-container": "#ff5451",
        "primary": "#ffb3ad",
        "error": "#ffb4ab",
        "on-surface": "#dae2fd",
        "on-error": "#690005",
        "surface-dim": "#0b1326",
        "on-primary": "#68000a",
        "on-secondary-container": "#004119",
        "surface-container-low": "#131b2e",
        "surface-container-high": "#222a3d",
        "on-primary-fixed-variant": "#930013",
        "background": "#0b1326",
        "on-surface-variant": "#e4beba",
        "secondary": "#4ae176",
        "surface-variant": "#2d3449",
        "on-primary-fixed": "#410004",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#ffdad7",
        "secondary-fixed": "#6bff8f",
        "tertiary-container": "#b68a00",
        "inverse-on-surface": "#283044",
        "secondary-container": "#00b954",
        "surface-container-highest": "#2d3449",
        "surface-bright": "#31394d",
        "surface": "#0b1326",
        "primary-fixed-dim": "#ffb3ad",
        "on-tertiary-fixed": "#251a00",
        "outline": "#ab8986",
        "on-tertiary-fixed-variant": "#5a4300"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "inter": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
